"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\CoreApplication.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Component\CameraComponent.h --absolute --package Foundation  -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Component\LightComponent.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Component\MeshRendererComponent.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Image\Texture.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Importer\Importer.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Manager\ --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Material\Shader.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Mesh\Mesh.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\RenderAPI\RenderAPI.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Renderer\ParamBlocks.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Renderer\Renderer.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Resource\Resource.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Resource\ResourceHandle.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Resource\Resources.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Scene\Actor.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Scene\Component.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Scene\SceneObject.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Scene\Scene.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility
"../../../cmake-build-debug/bin/quark-header-tool.exe" D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Scene\Transform.h --absolute --package Foundation -I D:\Projects\Quark\cmake-build-debug\Generated\Engine -I D:\Projects\Quark\cmake-build-debug\Generated\Utility

