start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\CoreApplication.h D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation
start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\RenderAPI\RenderAPI.h D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation

start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Manager\ D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation

rem start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Manager\BufferManager.h D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation
rem start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Manager\CommandBufferManager.h D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation
rem start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Manager\RenderAPI.h D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation
rem start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Manager\RenderAPIManager.h D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation
rem start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Manager\RenderStateManager.h D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation
rem start /d "../../../cmake-build-debug/bin/" quark-header-tool.exe D:\Projects\Quark\Source\Foundation\Core\ D:\Projects\Quark\Source\Foundation\Core\Manager\RenderWindowManager.h D:\Projects\Quark\Source\Foundation\Generated --absolute --package Foundation