#pragma once

#define DECLARE_EVENT(NAME) FUNC_DECLARE_EVENT(NAME, void)
#define DECLARE_EVENT_RetVal(NAME, RETVAL) FUNC_DECLARE_EVENT(NAME, RETVAL)

#define DECLARE_EVENT_ParamOne(NAME, PARAM1TYPE) FUNC_DECLARE_EVENT(NAME, void, PARAM1TYPE)
#define DECLARE_EVENT_RetVal_ParamOne(NAME, RETVAL, PARAM1TYPE) FUNC_DECLARE_EVENT(NAME, RETVAL, PARAM1TYPE)

#define DECLARE_EVENT_ParamTwo(NAME, PARAM1TYPE, PARAM2TYPE) FUNC_DECLARE_EVENT(NAME, void, PARAM1TYPE, PARAM2TYPE)
#define DECLARE_EVENT_RetVal_ParamTwo(NAME, RETVAL, PARAM1TYPE, PARAM2TYPE) FUNC_DECLARE_EVENT(NAME, RETVAL, PARAM1TYPE, PARAM2TYPE)